on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      # Download repository code onto the runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: greetings
        run: echo "hello world"
